logger:
  level: INFO
server:
  http_bind_address: :8080
  http_read_timeout: 5s
  http_write_timeout: 5s
  http_idle_timeout: 5s
previewer:
  request_timeout: 1s
  cache_size: 3
  cache_dir: /etc/previewer/cache
